void main(){
  int a = 2;
  int b = 1;
  print(a+b);
  String firstName = 'Jeongjoo';
  String lastName = 'Lee';
  String fullName = lastName + '' + firstName;
  print(fullName);
  print(a-b);
  print(-a);
  int a1 = 6;
  int b1 = 3;
  print(a1*b1);
  print('*'*5);
  int a2 = 10;
  int b2 = 4;
  print(a2/b2);
  print(a2~/b2);
  print(a2%b2);
  int a3 = 0;
  print(++a3);
  print(a3);
  print(a3++);
  print(a3);
  int b3 = 1;
  print(--b3);
  print(b3);
  print(b3--);
  print(b3);
  int a4 = 2;
  int b4 = 1;
  print(a4==b4);
  print(a4!=b4);
  print(a4>b4);
  print(a4<b4);
  print(a4>=b4);
  print(a4<=b4);
  int a5 = 1;
  print(a5);
  a5 = 2;
  print(a5);
  bool result = a4 > b4;
  print(!result);
  int a6 = 3;
  int b6 = 2;
  int c6 = 1;
  print(a6>b6);
  print(b6<c6);
  print(a6>b6 || b6<c6 );
  print(a6>b6 && b6<c6);
}